# https://docs.travis-ci.com/user/travis-lint

language: node_js

node_js:
  - 10
  - 14

script:
  - node_version=$(node -v); if [ ${node_version:1:2} = 10 ]; then npm run build && npm run lint && npm run coverage:node10; else npm run test; fi
